version: '3.7'
services:
  vue:
    build:
      context: ./dev/vue
    container_name: tech-blog-vue
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./vue:/app
    tty: true
    command: sh -c "yarn install && yarn serve"

  go:
    build:
      context: ./dev/go
    container_name: tech-blog-go
    ports:
      - 8082:8082
    environment:
      DSN: "root:password@tcp(host.docker.internal:3306)/tech-blog?parseTime=true"
      GOOGLE_APPLICATION_CREDENTIALS: "/go/src/app/tech-blog-46ddd-firebase-adminsdk-yhjjs-9fe209e75b.json"
    volumes:
      - ./go:/go/src
    tty: true
    command: fresh

  nginx:
    image: nginx
    container_name: tech-blog-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./dev/nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:8
    container_name: tech-blog-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: techblog
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
